AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Vanta Vulnerability Statistics - Lambda Functions

  Optimized Lambda deployment with performance enhancements:
  - Tuned memory and timeout settings
  - Dead Letter Queues for error handling
  - CloudWatch alarms for monitoring
  - Lambda SnapStart support (Python 3.11+)
  - Connection pooling and lazy imports

Globals:
  Function:
    # Global defaults for all Lambda functions
    Runtime: python3.11  # Use Python 3.11 for SnapStart support
    Timeout: 300  # 5 minutes
    MemorySize: 1024  # Optimized for performance (can be tuned per function)
    Environment:
      Variables:
        # Performance optimization settings
        MAX_POOL_CONNECTIONS: 50
        POWERTOOLS_SERVICE_NAME: vanta-vuln-stats
        POWERTOOLS_METRICS_NAMESPACE: VantaVulnStats
        LOG_LEVEL: INFO
        # Enable Lambda Insights for enhanced monitoring
        AWS_LAMBDA_INSIGHTS_VERSION: !Ref LambdaInsightsExtensionArn
    Tracing: Active  # Enable X-Ray tracing for performance analysis
    Layers:
      - !Ref DependenciesLayer
      - !Ref LambdaInsightsExtension

Parameters:
  VantaCredentialsSecretName:
    Type: String
    Default: vanta-api-credentials
    Description: Name of Secrets Manager secret containing Vanta API credentials

  S3BucketName:
    Type: String
    Default: vanta-vuln-data
    Description: S3 bucket name for storing vulnerability data

  AlarmEmail:
    Type: String
    Description: Email address for CloudWatch alarm notifications
    Default: ''

  LambdaInsightsExtensionArn:
    Type: String
    Description: ARN of Lambda Insights extension layer
    Default: arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:21
    # Update region as needed - see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versions.html

Resources:
  # ====================
  # Lambda Layers
  # ====================

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: vanta-vuln-dependencies
      Description: Python dependencies for Vanta vulnerability functions
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.11
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

  # ====================
  # Dead Letter Queues
  # ====================

  SyncFunctionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: vanta-vuln-sync-dlq
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Purpose
          Value: DLQ for failed sync invocations

  # ====================
  # Lambda Functions
  # ====================

  VantaSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vanta-vuln-sync
      Description: Syncs vulnerability data from Vanta API to S3 with performance optimizations
      CodeUri: .
      Handler: lambda_handlers.sync_handler.lambda_handler
      # Optimized resource allocation based on profiling
      MemorySize: 1536  # Higher memory = more CPU for faster API calls
      Timeout: 900  # 15 minutes for large datasets
      ReservedConcurrentExecutions: 5  # Limit concurrent executions to avoid rate limiting
      # Dead Letter Queue configuration
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt SyncFunctionDLQ.Arn
      Environment:
        Variables:
          VANTA_CREDENTIALS_SECRET: !Ref VantaCredentialsSecretName
          S3_BUCKET: !Ref S3BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${VantaCredentialsSecretName}*'
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SyncFunctionDLQ.Arn
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: '*'
      Events:
        DailySync:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 6 * * ? *)'  # Run daily at 6 AM UTC
            Description: Daily vulnerability data sync
            Enabled: true
      # Enable SnapStart for faster cold starts (Python 3.11+)
      # Note: SnapStart requires specific runtime and configuration
      # AutoPublishAlias: live
      # SnapStart:
      #   ApplyOn: PublishedVersions

  # ====================
  # S3 Bucket
  # ====================

  VulnerabilityDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: STANDARD_IA
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 365
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Purpose
          Value: Vanta vulnerability data storage

  # ====================
  # CloudWatch Alarms
  # ====================

  SyncFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vanta-vuln-sync-errors
      AlarmDescription: Alert when sync function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref VantaSyncFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !If [HasAlarmEmail, !Ref AlarmTopic, !Ref AWS::NoValue]

  SyncFunctionThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vanta-vuln-sync-throttles
      AlarmDescription: Alert when sync function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref VantaSyncFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !If [HasAlarmEmail, !Ref AlarmTopic, !Ref AWS::NoValue]

  SyncFunctionDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vanta-vuln-sync-duration
      AlarmDescription: Alert when sync function duration is too high
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 600000  # 10 minutes (in milliseconds)
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref VantaSyncFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !If [HasAlarmEmail, !Ref AlarmTopic, !Ref AWS::NoValue]

  SyncFunctionConcurrentExecutionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vanta-vuln-sync-concurrent-executions
      AlarmDescription: Alert when concurrent executions are high
      MetricName: ConcurrentExecutions
      Namespace: AWS/Lambda
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 4  # Close to ReservedConcurrentExecutions limit
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref VantaSyncFunction
      TreatMissingData: notBreaching
      AlarmActions:
        - !If [HasAlarmEmail, !Ref AlarmTopic, !Ref AWS::NoValue]

  DLQDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vanta-vuln-sync-dlq-depth
      AlarmDescription: Alert when messages are in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SyncFunctionDLQ.QueueName
      TreatMissingData: notBreaching
      AlarmActions:
        - !If [HasAlarmEmail, !Ref AlarmTopic, !Ref AWS::NoValue]

  # ====================
  # SNS Topic for Alarms
  # ====================

  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: HasAlarmEmail
    Properties:
      TopicName: vanta-vuln-alarms
      DisplayName: Vanta Vulnerability Stats Alarms
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: email

  # ====================
  # CloudWatch Dashboard
  # ====================

  PerformanceDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: vanta-vuln-performance
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", {"stat": "Sum", "label": "Invocations"}],
                  [".", "Errors", {"stat": "Sum", "label": "Errors"}],
                  [".", "Throttles", {"stat": "Sum", "label": "Throttles"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Sync Function Invocations",
                "period": 300,
                "dimensions": {"FunctionName": ["${VantaSyncFunction}"]}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Duration", {"stat": "Average", "label": "Avg Duration"}],
                  ["...", {"stat": "Maximum", "label": "Max Duration"}],
                  ["...", {"stat": "Minimum", "label": "Min Duration"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Sync Function Duration",
                "period": 300,
                "yAxis": {"left": {"label": "Milliseconds"}},
                "dimensions": {"FunctionName": ["${VantaSyncFunction}"]}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["VantaVulnStats", "VulnerabilitiesFetched", {"stat": "Sum"}],
                  [".", "RemediationsFetched", {"stat": "Sum"}],
                  [".", "RecordsStored", {"stat": "Sum"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Data Processing Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "ConcurrentExecutions", {"stat": "Maximum"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Concurrent Executions",
                "period": 60,
                "dimensions": {"FunctionName": ["${VantaSyncFunction}"]}
              }
            }
          ]
        }

Conditions:
  HasAlarmEmail: !Not [!Equals [!Ref AlarmEmail, '']]

Outputs:
  VantaSyncFunctionArn:
    Description: ARN of the Vanta Sync Lambda function
    Value: !GetAtt VantaSyncFunction.Arn
    Export:
      Name: VantaSyncFunctionArn

  VantaSyncFunctionName:
    Description: Name of the Vanta Sync Lambda function
    Value: !Ref VantaSyncFunction

  S3BucketName:
    Description: S3 bucket for vulnerability data
    Value: !Ref VulnerabilityDataBucket

  DLQUrl:
    Description: URL of the Dead Letter Queue
    Value: !Ref SyncFunctionDLQ

  DashboardUrl:
    Description: URL to CloudWatch Dashboard
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=vanta-vuln-performance'
